all.branches    <- diversitreeGP:::all.branches
make.cache      <- diversitreeGP:::make.cache
get.ordering    <- diversitreeGP:::get.ordering
root.p.xxsse    <- diversitreeGP:::root.p.xxsse
root.xxsse      <- diversitreeGP:::root.xxsse
cleanup         <- diversitreeGP:::cleanup
ll.xxsse        <- diversitreeGP:::ll.xxsse
make.branches   <- diversitreeGP:::make.branches
dt.tips.grouped <- diversitreeGP:::dt.tips.grouped
dt.tips.ordered <- diversitreeGP:::dt.tips.ordered

make.punctsse               <- diversitreeGP:::make.punctsse
print.punctsse              <- diversitreeGP:::print.punctsse
argnames.punctsse           <- diversitreeGP:::argnames.punctsse
find.mle.punctsse           <- diversitreeGP:::find.mle.punctsse
mcmc.punctsse               <- diversitreeGP:::mcmc.punctsse
initial.conditions.punctsse <- diversitreeGP:::initial.conditions.punctsse
make.branches.punctsse      <- diversitreeGP:::make.branches.punctsse
starting.point.punctsse     <- diversitreeGP:::starting.point.punctsse    
root.p.punctsse             <- diversitreeGP:::root.p.punctsse
root.punctsse               <- diversitreeGP:::root.punctsse
ll.xxsse.punctsse           <- diversitreeGP:::ll.xxsse.punctsse

make.bisse                <- diversitreeGP:::make.bisse
print.bisse               <- diversitreeGP:::print.bisse
argnames.bisse            <- diversitreeGP:::argnames.bisse
find.mle.bisse            <- diversitreeGP:::find.mle.bisse
mcmc.bisse                <- diversitreeGP:::mcmc.bisse
make.cache.bisse          <- diversitreeGP:::make.cache.bisse
initial.tip.bisse         <- diversitreeGP:::initial.tip.bisse
ll.bisse                  <- diversitreeGP:::ll.bisse
initial.conditions.bisse  <- diversitreeGP:::initial.conditions.bisse
make.branches.bisse       <- diversitreeGP:::make.branches.bisse
branches.unresolved.bisse <- diversitreeGP:::branches.unresolved.bisse
stationary.freq.bisse     <- diversitreeGP:::stationary.freq.bisse
starting.point.bisse      <- diversitreeGP:::starting.point.bisse
check.unresolved          <- diversitreeGP:::check.unresolved         

make.musse               <- diversitreeGP:::make.musse
print.musse              <- diversitreeGP:::print.musse
argnames.musse           <- diversitreeGP:::argnames.musse
find.mle.musse           <- diversitreeGP:::find.mle.musse
mcmc.musse               <- diversitreeGP:::mcmc.musse
make.cache.musse         <- diversitreeGP:::make.cache.musse
initial.tip.musse        <- diversitreeGP:::initial.tip.musse
initial.conditions.musse <- diversitreeGP:::initial.conditions.musse
make.branches.musse      <- diversitreeGP:::make.branches.musse
starting.point.musse     <- diversitreeGP:::starting.point.musse    

protect                <- diversitreeGP:::protect
invert                 <- diversitreeGP:::invert
boxconstrain           <- diversitreeGP:::boxconstrain
big.brother            <- diversitreeGP:::big.brother
make.ode               <- diversitreeGP:::make.ode
quadratic.roots        <- diversitreeGP:::quadratic.roots
discretize             <- diversitreeGP:::discretize
make.prior.exponential <- diversitreeGP:::make.prior.exponential
descendants            <- diversitreeGP:::descendants
ancestors              <- diversitreeGP:::ancestors
mrca.tipset            <- diversitreeGP:::mrca.tipset
branching.heights      <- diversitreeGP:::branching.heights
branching.depth        <- diversitreeGP:::branching.depth
matrix.to.list         <- diversitreeGP:::matrix.to.list
argnames.twopart       <- diversitreeGP:::argnames.twopart
argnames.twopart.set   <- diversitreeGP:::argnames.twopart.set  
